export const date = ["Today", "This Week", "This Month", "All Time"];

export const tableHead = ["#", "Artist", "Change", "NFTs Sold", "Volume"];

export const artistTodayData = [
  {
    id: 1,
    name: "Jaydon Ekstrom Bothman",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Jaydon.png",
  },
  {
    id: 2,
    name: "Ruben Carder",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Ruben.png",
  },
  {
    id: 3,
    name: "Alfredo Septimus",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Alfredo.png",
  },
  {
    id: 4,
    name: "Davis Franci",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Davis_Franci.png",
  },
  {
    id: 5,
    name: "Livia Rosser",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Livia.png",
  },
  {
    id: 6,
    name: "Kianna Donin",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Kianna_Donin.png",
  },
  {
    id: 7,
    name: "Philips Lipshutz",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Philip.png",
  },
  {
    id: 8,
    name: "Maria Rosser",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Maria.png",
  },
  {
    id: 9,
    name: "Kianna Stanton",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Kianna_Stanton.png",
  },
  {
    id: 10,
    name: "Angel Lubin",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Angel.png",
  },
  {
    id: 11,
    name: "Allison Torff",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Allison.png",
  },
  {
    id: 12,
    name: "Davis Workman",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Davis_Workman.png",
  },
  {
    id: 13,
    name: "Lindsey Lipshutz",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Lindsey.png",
  },
  {
    id: 14,
    name: "Randy Cader",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Randy.png",
  },
  {
    id: 15,
    name: "Lydia Culhane",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Lydia.png",
  },
  {
    id: 16,
    name: "Rayna Bator",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Rayna.png",
  },
  {
    id: 17,
    name: "Jocelyn Westervelt",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Jocelyn.png",
  },
  {
    id: 18,
    name: "Marilyn Torff",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Marilyn.png",
  },
  {
    id: 19,
    name: "Skylar Levin",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Skylar.png",
  },
  {
    id: 20,
    name: "Terry Dorwart",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Terry.png",
  },
];

export const artistThisWeekData = [
  {
    id: 1,
    name: "Marcus Saris",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Alfredo.png",
  },
  {
    id: 2,
    name: "Alfonso Bator",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Davis_Franci.png",
  },
  {
    id: 3,
    name: "Nolan Mango",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Jaydon.png",
  },
  {
    id: 4,
    name: "Miracle Gouse",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Ruben.png",
  },
  {
    id: 5,
    name: "Rosser Livia",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Livia.png",
  },
  {
    id: 6,
    name: "Alenna Septimus",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Philip.png",
  },
  {
    id: 7,
    name: "Desirae Lipshutz",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Maria.png",
  },
  {
    id: 8,
    name: "Paityn Kenter",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Kianna_Donin.png",
  },
  {
    id: 9,
    name: "Hanna Culhane",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Kianna_Stanton.png",
  },
  {
    id: 10,
    name: "Angel Lubin",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Angel.png",
  },
  {
    id: 11,
    name: "Allison Torff",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Allison.png",
  },
  {
    id: 12,
    name: "Davis Workman",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Davis_Workman.png",
  },
  {
    id: 13,
    name: "Lindsey Lipshutz",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Lindsey.png",
  },
  {
    id: 14,
    name: "Randy Cader",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Randy.png",
  },
  {
    id: 15,
    name: "Lydia Culhane",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Lydia.png",
  },
  {
    id: 16,
    name: "Rayna Bator",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Rayna.png",
  },
  {
    id: 17,
    name: "Jocelyn Westervelt",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Jocelyn.png",
  },
  {
    id: 18,
    name: "Marilyn Torff",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Terry.png",
  },
  {
    id: 19,
    name: "Skylar Levin",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Skylar.png",
  },
  {
    id: 20,
    name: "Skylar Mango",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Marilyn.png",
  },
];

export const artistThisMonthData = [
  {
    id: 1,
    name: "Zain Dokidis",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Terry.png",
  },
  {
    id: 2,
    name: "Ruben Vetros",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Davis_Franci.png",
  },
  {
    id: 3,
    name: "Alfredo Septimus",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Alfredo.png",
  },
  {
    id: 4,
    name: "Emerson Carder",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Ruben.png",
  },
  {
    id: 5,
    name: "Maren Franci",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Livia.png",
  },
  {
    id: 6,
    name: "Kianna Donin",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Kianna_Donin.png",
  },
  {
    id: 7,
    name: "Philips Lipshutz",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Philip.png",
  },
  {
    id: 8,
    name: "Maria Rosser",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Maria.png",
  },
  {
    id: 9,
    name: "Ekstrom Bothman",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Kianna_Stanton.png",
  },
  {
    id: 10,
    name: "Angel Lubin",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Angel.png",
  },
  {
    id: 11,
    name: "Allison Torff",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Allison.png",
  },
  {
    id: 12,
    name: "Davis Workman",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Davis_Workman.png",
  },
  {
    id: 13,
    name: "Lindsey Lipshutz",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Lindsey.png",
  },
  {
    id: 14,
    name: "Randy Cader",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Randy.png",
  },
  {
    id: 15,
    name: "Lydia Culhane",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Lydia.png",
  },
  {
    id: 16,
    name: "Rayna Bator",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Rayna.png",
  },
  {
    id: 17,
    name: "Jocelyn Westervelt",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Jocelyn.png",
  },
  {
    id: 18,
    name: "Marilyn Torff",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Marilyn.png",
  },
  {
    id: 19,
    name: "Skylar Levin",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Skylar.png",
  },
  {
    id: 20,
    name: "Terry Dorwart",
    change: 1.41,
    nftsSold: 602,
    volume: 12.4,
    img: "../../src/assets/images/rankings/Jaydon.png",
  },
];
